### ISSUE TITLE
[Chapter2] Installation using Packstack

### ISSUE THREAD

**Issue by akshaygin** [enhance-manageiq/docs#18]
IMO, It should contains atleast these points:
- [x] RDO and Packstack
- [x] Installation Guide
- [x] System Specification
- [x] Installation Issue

Addition points related to topic are welcome

**Comment by son-vyas** [comment]
@akshay196  I think only the stuffs related to the issue let be discussed here as the RDO and packstack and all other things are already going to be covered in [chapter2](https://github.com/enhance-manageiq/docs/blob/master/chapter2/installation_packstack.md.)
Let's not repeat the content.

**Comment by akshaygin** [comment]
Completed in #22
